name: Test and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Run workflow on push to the main branch

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run JavaScript test file
      run: node test/test.js # Run the JavaScript test file

    # Upload build output as an artifact (if applicable)
    - name: Upload artifact for GitHub Pages
      if: success() # Only upload if the test passed
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./ # The directory containing files to deploy (adjust if needed)

  # Deployment job
  deploy:
    needs: test # Only run this job if the test job succeeds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Grant permission to write to GitHub Pages
      id-token: write   # Grant permission to verify the deployment origin

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages # Must match the name used in upload
